version: '3.8'
services:
  postgresdb:
    image: mysql:8.0
    environment:
      - MYSQL_USER=jonataslaet
      - MYSQL_PASSWORD=blendo273
      - MYSQL_ROOT_PASSWORD=blendo273
      - MYSQL_DATABASE=dblaetstore
    ports:
      - '3306:3306'
